global using System;
global using System.Collections;
global using System.Collections.Generic;
global using System.ComponentModel;
global using System.Diagnostics.CodeAnalysis;
global using System.Linq;
global using System.Numerics;
global using System.Runtime.CompilerServices;
global using System.Runtime.InteropServices;
global using System.Text;
global using System.Threading;
global using MahjongMatch.Concepts;
global using MahjongMatch.Concepts.Primitives;
global using MahjongMatch.Linq;
global using LayerIndex = sbyte;
